-- Bulletin Phase 6: specialist technology, science, health, and climate feeds.
--
-- These nine official RSS endpoints were re-checked immediately before this
-- migration was finalized. Activation remains fail-closed and limited to the
-- feed-supplied metadata/excerpt/link scope recorded for each source. Publisher
-- attribution must be preserved, and every usage decision must be re-reviewed
-- before an external or commercial launch.

with specialist_catalogue (
  id, catalogue_key, publisher_name, feed_name, feed_url, publisher_domain,
  publisher_home_url, category_scope, language, country_code, state_region,
  expected_update_interval, reliability, role, is_institutional, terms_notes,
  feed_format, allowed_hosts, usage_review_url, verification_notes, parser_notes
) as (
  values
    (
      '60000000-0000-4000-8000-000000000087'::uuid,
      'gadgets-360-latest',
      'Gadgets 360',
      'Latest',
      'https://feeds.feedburner.com/gadgets360-latest',
      'gadgets360.com',
      'https://www.gadgets360.com/',
      array['technology-ai']::public.news_category[],
      'en'::public.briefing_language,
      'IN',
      null,
      interval '20 minutes',
      'tier-1'::public.source_reliability,
      'primary'::public.source_role,
      false,
      'Official Gadgets 360 feed listed in the NDTV RSS directory. Approved only for Bulletin current private, personal, non-commercial metadata/excerpt/link scope with original attribution; re-review before external or commercial launch.',
      'rss-2.0',
      array['feeds.feedburner.com'],
      'https://www.ndtv.com/rss',
      'Valid RSS 2.0 over HTTPS; 100 items and a current 18 July 2026 build timestamp at final verification.',
      null
    ),
    (
      '60000000-0000-4000-8000-000000000088',
      'tech-xplore-ai-machine-learning',
      'Tech Xplore',
      'Artificial Intelligence and Machine Learning',
      'https://techxplore.com/rss-feed/breaking/machine-learning-ai-news/',
      'techxplore.com',
      'https://techxplore.com/',
      array['technology-ai']::public.news_category[],
      'en',
      null,
      null,
      interval '30 minutes',
      'tier-1',
      'supplementary',
      false,
      'Official Tech Xplore feed directory permits attributed personal and commercial RSS syndication while keeping headlines and links unchanged.',
      'rss-2.0',
      array['techxplore.com'],
      'https://techxplore.com/feeds/',
      'Valid RSS 2.0 over HTTPS; 30 current items at final verification. The endpoint expects an honest descriptive reader User-Agent, which Bulletin already sends.',
      'Fetch with Bulletin descriptive metadata-reader User-Agent; do not impersonate a browser.'
    ),
    (
      '60000000-0000-4000-8000-000000000089',
      'phys-org-science-technology',
      'Phys.org',
      'Science and Technology Spotlight',
      'https://phys.org/rss-feed/breaking/',
      'phys.org',
      'https://phys.org/',
      array['science']::public.news_category[],
      'en',
      null,
      null,
      interval '30 minutes',
      'tier-1',
      'supplementary',
      false,
      'Official Phys.org feed directory permits attributed personal and commercial RSS syndication while keeping headlines and links unchanged.',
      'rss-2.0',
      array['phys.org'],
      'https://phys.org/feeds/',
      'Valid RSS 2.0 over HTTPS; 30 current items at final verification. The endpoint expects an honest descriptive reader User-Agent, which Bulletin already sends.',
      'Fetch with Bulletin descriptive metadata-reader User-Agent; do not impersonate a browser.'
    ),
    (
      '60000000-0000-4000-8000-000000000090',
      'nasa-news-releases',
      'NASA',
      'News Releases',
      'https://www.nasa.gov/news-release/feed/',
      'nasa.gov',
      'https://www.nasa.gov/',
      array['science']::public.news_category[],
      'en',
      'US',
      null,
      interval '60 minutes',
      'tier-1',
      'supplementary',
      true,
      'Official NASA news-release RSS. Use NASA attribution and preserve any separately credited third-party material; re-review the NASA media rules before external launch.',
      'rss-2.0',
      array['www.nasa.gov'],
      'https://www.nasa.gov/nasa-brand-center/images-and-media/',
      'Valid RSS 2.0 over HTTPS; 10 current news releases at final verification.',
      null
    ),
    (
      '60000000-0000-4000-8000-000000000091',
      'medical-xpress-health',
      'Medical Xpress',
      'Health and Medical Research Spotlight',
      'https://medicalxpress.com/rss-feed/breaking/',
      'medicalxpress.com',
      'https://medicalxpress.com/',
      array['health']::public.news_category[],
      'en',
      null,
      null,
      interval '30 minutes',
      'tier-1',
      'supplementary',
      false,
      'Official Medical Xpress feed directory permits attributed personal and commercial RSS syndication while keeping headlines and links unchanged.',
      'rss-2.0',
      array['medicalxpress.com'],
      'https://medicalxpress.com/feeds/',
      'Valid RSS 2.0 over HTTPS; 30 current items at final verification. The endpoint expects an honest descriptive reader User-Agent, which Bulletin already sends.',
      'Fetch with Bulletin descriptive metadata-reader User-Agent; do not impersonate a browser.'
    ),
    (
      '60000000-0000-4000-8000-000000000092',
      'who-news-english',
      'World Health Organization',
      'News — English',
      'https://www.who.int/rss-feeds/news-english.xml',
      'who.int',
      'https://www.who.int/',
      array['health']::public.news_category[],
      'en',
      null,
      null,
      interval '60 minutes',
      'tier-1',
      'supplementary',
      true,
      'Official WHO news RSS. Approved only for Bulletin current private, non-commercial metadata/excerpt/link scope with acknowledgement; WHO permission and terms must be re-reviewed before external or commercial launch.',
      'rss-2.0',
      array['www.who.int'],
      'https://www.who.int/about/policies/publishing/copyright',
      'Valid RSS 2.0 over HTTPS; 25 current English news items at final verification.',
      null
    ),
    (
      '60000000-0000-4000-8000-000000000093',
      'mongabay-india-climate',
      'Mongabay India',
      'Climate Change',
      'https://india.mongabay.com/tag/climate-change/feed/',
      'india.mongabay.com',
      'https://india.mongabay.com/',
      array['climate']::public.news_category[],
      'en',
      'IN',
      null,
      interval '45 minutes',
      'tier-1',
      'primary',
      false,
      'Official Mongabay India topic feed. Mongabay India publishes under CC BY-ND 4.0; retain attribution and links and do not adapt publisher material.',
      'rss-2.0',
      array['india.mongabay.com'],
      'https://india.mongabay.com/about/',
      'Valid RSS 2.0 over HTTPS; 20 current India climate items at final verification.',
      null
    ),
    (
      '60000000-0000-4000-8000-000000000094',
      'mongabay-hindi-climate',
      'Mongabay Hindi',
      'जलवायु परिवर्तन',
      'https://hindi.mongabay.com/tag/climate-change/feed/',
      'hindi.mongabay.com',
      'https://hindi.mongabay.com/',
      array['climate']::public.news_category[],
      'hi',
      'IN',
      null,
      interval '45 minutes',
      'tier-1',
      'primary',
      false,
      'Official Mongabay Hindi topic feed under Mongabay India CC BY-ND 4.0 terms; retain attribution and links and do not adapt publisher material.',
      'rss-2.0',
      array['hindi.mongabay.com'],
      'https://india.mongabay.com/about/',
      'Valid Hindi RSS 2.0 over HTTPS; 30 current climate items at final verification.',
      null
    ),
    (
      '60000000-0000-4000-8000-000000000095',
      'carbon-brief-latest',
      'Carbon Brief',
      'Latest',
      'https://www.carbonbrief.org/feed/',
      'carbonbrief.org',
      'https://www.carbonbrief.org/',
      array['climate']::public.news_category[],
      'en',
      'GB',
      null,
      interval '60 minutes',
      'tier-1',
      'supplementary',
      false,
      'Official Carbon Brief feed. Approved only for Bulletin current private, non-commercial metadata/excerpt/link scope with credit and links; contact Carbon Brief before commercial use or adaptation.',
      'rss-2.0',
      array['www.carbonbrief.org'],
      'https://www.carbonbrief.org/about-us/',
      'Valid RSS 2.0 over HTTPS; 10 current items at final verification.',
      null
    )
)
insert into public.sources (
  id, catalogue_key, publisher_name, feed_name, feed_url, publisher_domain,
  publisher_home_url, category_scope, language, country_code, state_region,
  expected_update_interval, reliability, role, is_aggregator, is_institutional,
  terms_status, terms_notes, is_active, health, next_fetch_at, feed_format,
  allowed_hosts, usage_review_url, usage_reviewed_at, technical_status,
  verification_checked_at, verification_http_status, verification_notes,
  disabled_reason, parser_notes
)
select
  id, catalogue_key, publisher_name, feed_name, feed_url, publisher_domain,
  publisher_home_url, category_scope, language, country_code, state_region,
  expected_update_interval, reliability, role, false, is_institutional,
  'approved'::public.terms_review_status, terms_notes, true,
  'unknown'::public.source_health, statement_timestamp(), feed_format,
  allowed_hosts, usage_review_url, '2026-07-18 16:20:00+05:30'::timestamptz,
  'verified', '2026-07-18 16:20:00+05:30'::timestamptz, 200,
  verification_notes, null, parser_notes
from specialist_catalogue;
