import { z } from "zod";

export const serverEnvironmentSchema = z.object({
  APP_ENV: z.enum(["development", "test", "production"]).default("development"),
  LOG_LEVEL: z.enum(["debug", "info", "warn", "error"]).default("info"),
  APP_BASE_URL: z.string().url().optional(),
  SUPABASE_URL: z.string().url().optional(),
  SUPABASE_ANON_KEY: z.string().min(1).optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1).optional(),
  MANAGEMENT_LINK_SIGNING_SECRET: z.string().min(32).optional(),
  SESSION_SIGNING_SECRET: z.string().min(32).optional(),
  EMAIL_TRANSPORT: z.enum(["test", "smtp"]).default("test"),
  GEMINI_API_KEY: z.string().min(1).optional(),
  GROQ_API_KEY: z.string().min(1).optional(),
  GMAIL_SMTP_USER: z.string().email().optional(),
  GMAIL_SMTP_APP_PASSWORD: z.string().min(1).optional(),
  OWNER_EMAIL: z.string().email().optional(),
  CRON_SHARED_SECRET: z.string().min(32).optional(),
  INGESTION_BATCH_SIZE: z.coerce.number().int().min(1).max(10).default(4),
  INGESTION_LEASE_SECONDS: z.coerce.number().int().min(60).max(900).default(300),
  INGESTION_TIMEOUT_MS: z.coerce.number().int().min(1_000).max(15_000).default(8_000),
  INGESTION_MAX_RESPONSE_BYTES: z.coerce.number().int().min(64 * 1024).max(5 * 1024 * 1024).default(2 * 1024 * 1024),
  INTELLIGENCE_PROVIDER: z.enum(["disabled", "gemini", "groq"]).default("disabled"),
  INTELLIGENCE_BATCH_SIZE: z.coerce.number().int().min(1).max(25).default(5),
  INTELLIGENCE_LEASE_SECONDS: z.coerce.number().int().min(60).max(900).default(300),
  INTELLIGENCE_CANDIDATE_LIMIT: z.coerce.number().int().min(1).max(20).default(12),
  INTELLIGENCE_CANDIDATE_LOOKBACK_HOURS: z.coerce.number().int().min(1).max(168).default(96),
  SHARED_SUMMARY_BATCH_SIZE: z.coerce.number().int().min(1).max(10).default(4),
  SHARED_SUMMARY_LEASE_SECONDS: z.coerce.number().int().min(60).max(900).default(420),
  DELIVERY_SCHEDULER_BATCH_SIZE: z.coerce.number().int().min(1).max(200).default(50),
  PERSONALIZATION_BATCH_SIZE: z.coerce.number().int().min(1).max(50).default(10),
  PERSONALIZATION_LEASE_SECONDS: z.coerce.number().int().min(60).max(900).default(180),
  DELIVERY_BATCH_SIZE: z.coerce.number().int().min(1).max(50).default(10),
  DELIVERY_LEASE_SECONDS: z.coerce.number().int().min(60).max(900).default(300),
  BACKUP_STORAGE_ADAPTER: z.enum(["local", "google-drive", "fake"]).default("local"),
  BACKUP_DATABASE_URL: z.string().url().optional(),
  BACKUP_ENCRYPTION_KEY: z.string().min(43).optional(),
  BACKUP_LOCAL_DIRECTORY: z.string().min(1).optional(),
  GOOGLE_DRIVE_BACKUP_FOLDER_ID: z.string().min(1).optional(),
  GOOGLE_DRIVE_CLIENT_ID: z.string().min(1).optional(),
  GOOGLE_DRIVE_CLIENT_SECRET: z.string().min(1).optional(),
  GOOGLE_DRIVE_REFRESH_TOKEN: z.string().min(1).optional(),
  BACKUP_UTC_HOUR: z.coerce.number().int().min(0).max(23).default(2),
  PROVIDER_TIMEOUT_MS: z.coerce.number().int().min(1_000).max(60_000).default(20_000),
  PROVIDER_MAX_ATTEMPTS: z.coerce.number().int().min(1).max(3).default(1),
  PROVIDER_REQUESTS_PER_MINUTE: z.coerce.number().int().min(1).max(10_000).default(25),
  PROVIDER_INPUT_UNITS_PER_MINUTE: z.coerce.number().int().min(1).max(100_000_000).default(5_500),
  PROVIDER_REQUESTS_PER_DAY: z.coerce.number().int().min(2).max(10_000_000).default(900),
  PROVIDER_INPUT_UNITS_PER_DAY: z.coerce.number().int().min(1).max(1_000_000_000).default(160_000),
  GEMINI_GENERATION_MODEL: z.string().trim().min(1).max(120).default("gemini-3.1-flash-lite"),
  GROQ_GENERATION_MODEL: z.string().trim().min(1).max(120).default("openai/gpt-oss-20b"),
});

export type ServerEnvironment = z.infer<typeof serverEnvironmentSchema>;
